### ISSUE TITLE
Compile instructions for RHEL/CentOS installation?

### ISSUE THREAD

**Issue by dachshund-digital** [Rajpratik71/Realtek-rtl8811AU_8812AU_8821AU_linux-source-code#1]
Compile instructions for RHEL/CentOS installation?

**Comment by rajpratik71** [comment]
Firstly Install kernel headers and other dependencies.

sudo yum -y install epel-release
sudo yum -y update
sudo yum -y install \
  wget \
  bzip2 \
  gcc \
  gcc-c++ \
  gcc-gfortran \
  make \
  git \
  zlib-devel
sudo yum clean all

**Comment by rajpratik71** [comment]
Copy the Source in /usr/src/

# cd /usr/src/rtl8812AU_8821AU_linux

# sudo make clean

# sudo make

# sudo make install

# sudo modprobe -a 8812au

**Comment by dachshund-digital** [comment]
Thanks, very much!
